### ISSUE TITLE
Implement simple sound

### ISSUE THREAD

**Issue by ucodelukas** [le-doux/bitsy#106]
Examples, 
![Screenshot_20200730-214240](https://user-images.githubusercontent.com/66177541/88969264-d8b46700-d2b0-11ea-8fea-f365dc17f342.png)

https://github.com/zenzoa/beepster
https://github.com/adamonsoon/rtttl-parse

**Comment by le-doux** [comment]
thanks for the suggestion! sound & music were added in 8.0 so I'm closing this :)

https://ledoux.itch.io/bitsy/devlog/402168/bitsy-80
