### ISSUE TITLE
Exits with associated blank Dialogs do not work

### ISSUE THREAD

**Issue by spdrcstl** [le-doux/bitsy#107]
**Issue**

An Exit that has an associated Dialog, that is itself blank, will fail to trigger when the player moves onto the exit tile.

**Steps to Reproduce**

1. Create a room with an exit.
2. Add a new dialog to the exit (using either UI or manual game data edit).
3. Delete all text / UI boxes for that associated dialog, so that it is blank.
4. Play game and attempt to move through exit.

**Expected Results**

Player moves through the exit to the new room or location, with no dialog displayed.

**Actual Results**

Player steps onto the tile containing the exit, but nothing happens.

Should any text be added to the dialog, it will start to work, and if the text is deleted, it will stop working again.
Exits without attached dialogs at all still function correctly.

**Affected Version**

Bitsy 7.1

**Bug source**

Discord: users Auderox#6868, medusamae#6644, and Em#5537

**Comment by le-doux** [comment]
thanks for the really good bug writeup! this will be fixed in version 7.2 :)
