### ISSUE TITLE
Branch list `-` char at the start of dialog

### ISSUE THREAD

**Issue by saddy4** [le-doux/bitsy#111]
If the user creates a branching list, adds a dialog as a result of a branch test, and the dialog starts with the character `-`, the dialog became a branch. 

I think this happens because of how the parse handles the dialog in the branching list.

**Comment by le-doux** [comment]
thanks for the report saddy! :)

**Comment by le-doux** [comment]
still an issue - I will keep this around to look into this next time I work on the dialog tool :)

**Comment by le-doux** [comment]
potential fix: allow escaping "-" with a backslash "\-"
