### ISSUE TITLE
Resized Dialog panel creates Scrollbars at original width

### ISSUE THREAD

**Issue by spdrcstl** [le-doux/bitsy#113]
**Issue** 

If the user attempts to resize the Dialog panel to make entry of long text easier, but does not resize an individual dialog line _vertically_, then it will create a scrollbar fixed at the original width of the dialog.

**Reproduction**

1. Open the dialog editor and create a new dialog entry - for instance, a Sequence.
2. Resize the whole dialog panel to be wider.
3. Enter enough text in the dialog to require a scrollbar.

**Expected Results**
Dialog entry box's width for calculating scrollbars is adjusted in accordance with the dialog panel's resized dimensions, and displays a scrollbar at the right hand side of the dialog entry.

**Actual Results**
Scrollbar's requirement and location is fixed to the dialog entry box's original size:
![image](https://user-images.githubusercontent.com/63952301/99878779-9e742a00-2bff-11eb-85d5-21475d4a5644.png)

**Affected Version**
Bitsy 7.2

**Comment by le-doux** [comment]
thanks pointing this out @spdrcstl! (and sorry I'm only getting around to replying now 😬)

this should be fixed now :)
