### ISSUE TITLE
Bitsy breaks in a confusing manner when "block third party cookies" is enabled

### ISSUE THREAD

**Issue by weeble** [le-doux/bitsy#114]
If third party cookies are disabled in Chrome, you get no data in various parts of the UI, and most actions simply don't work. But there's just enough working (e.g. opening and closing windows, toggling buttons) that if you're a bit clueless like me you just think you've not understood how it's supposed to work.

Here's what it looks like:

![image](https://user-images.githubusercontent.com/663664/100659119-10f3b100-3348-11eb-86f3-380da20882ff.png)

And here's a screenshot of the Javascript console:

![image](https://user-images.githubusercontent.com/663664/100659467-94150700-3348-11eb-8970-fd47f44a3769.png)

It was this message that clued me in to it being a cookies problem:

```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at start (https://v6p9d9t4.ssl.hwcdn.net/html/2580004/editor/script/editor.js:922:2)
    at onload (https://v6p9d9t4.ssl.hwcdn.net/html/2580004/editor/index.html:56:25)
```

Ideally it shouldn't need third party cookies at all. I think this happens because the scripts are served from a different domain from the page. But it would also probably be fine if it detected this and gave a clear message about what's wrong and how to fix it.

**Comment by synth-ruiner** [comment]
see also #94. it's just Itch that uses an external CDN - the version on bitsy.org is fine, at least.

**Comment by le-doux** [comment]
thanks for the report! this should be fixed now - please re-open it if you run into this problem again :)
