### ISSUE TITLE
Keyboard avatar movement doesn't work on a Microsoft Surface Pro

### ISSUE THREAD

**Issue by Sumaleth-zz** [le-doux/bitsy#115]
Arrow keys and AWSD don't move the player avatar in Bitsy games on a Microsoft Surface Pro.
- touch-screen swipes still move the avatar correctly so it's only the keyboard controls that exhibit this problem.
- this is experienced in both final Bitsy .html games and also in the Editor play mode.
- this was tested on Firefox and Windows 10; both are the same versions that I use on my desktop PC where the controls work fine.

**Comment by le-doux** [comment]
hi, I don't have the correct hardware to test this issue, so I'm closing it for now. if you have time to test it on your surface pro (no worries if you don't), let me know if it's still happening and we can re-open the issue!
