### ISSUE TITLE
Feature request: branching dialogue.

### ISSUE THREAD

**Issue by brancoliticus** [le-doux/bitsy#131]
I would like to see the possibility of creating branching dialogue between the avatar of the player and NPCs in the created game world in the base bitsy, without having to rely on hacks.

**Comment by le-doux** [comment]
I don't currently have plans to add branching dialog

it is possible to create a "menu" using a room with different exits as options though - I do something like that in my most recent game: https://ledoux.itch.io/we-fly-the-loop
