### ISSUE TITLE
Missing ability to localize

### ISSUE THREAD

**Issue by equaa** [le-doux/bitsy#135]
going to keep a list of things i find which aren't localized at all here as i find them

- "title" and other attributes in bitsy's ui
  - i was originally going to suggest some sort of "localization" class to each element to translate things like this, but it looks like this already exists. however, it is fixed to replace the inner text of the element with the class after it in the class list. what if we used some sort of `data-inner-text` or `data-title-text` attribute to mark these instead?
- the about text/link to tutorial
  - looking through the tsv we used to have a tutorial, although now it's a link. if that tutorial is too outdated and is better off as its own document, maybe we could just find translations of these/ask permission to translate the existing one? not sure

**Comment by equaa** [comment]
- lots of hacky string concatenations (such as https://github.com/le-doux/bitsy/blob/4d02c76fdc43ccc7f8416a76d26c883deffaab7a/editor/script/dialog_editor.js#L2169) make odd assumptions about punctuation and grammar instead of a more flexible way to do dynamic strings
- strings are reused in weird ways (probably to fill the gap with existing localization work?), such as reusing "exit_label" to both refer to the single side of two-sided and one-sided exits in the exit tool, but also marking the exit as a whole in the find tool

**Comment by le-doux** [comment]
thanks for this feedback @equaa!

I think the ability to localize title/tooltip text would be super awesome - not sure when I'll have time to get to it, but I'm going to leave it on the backlog for future consideration :)

**Comment by le-doux** [comment]
ability to localize tooltips is now available in newer tools - I'm adding them in as I go
