### ISSUE TITLE
>= operator is broken in 6.0

### ISSUE THREAD

**Issue by Ayolland** [le-doux/bitsy#14]
The Greater-than-or-equals operator is returning true in all cases. Of the logic operators in the editor, only '>=' appears affected.
  
<img width="1113" alt="Screen Shot 2019-04-17 at 9 40 16 AM" src="https://user-images.githubusercontent.com/10699280/56297440-efec3700-60f5-11e9-96c3-8dcdc8d70c9a.png">

**Comment by le-doux** [comment]
I'm looking into this now! thanks :)

**Comment by le-doux** [comment]
I think I have a fix for this now!
