### ISSUE TITLE
Feature request: add explicit controller buttons on mobile

### ISSUE THREAD

**Issue by tupini07** [le-doux/bitsy#144]
Right now, bitsy games can be played on mobile and for the player to move the avatar they need to drag on the touch screen.

It would be nice if instead of this, bitsy could show explicit controller buttons when the game is being played on mobile. As an example, the following is how a Pico8 game looks when played on mobile:  

<img src="https://user-images.githubusercontent.com/3422347/151448411-f00621fe-a7fc-4b85-89f0-81de95aee303.png" width="220" height="auto">

Of course, bitsy would only need one _interact_ button and the directional pad

btw, thank you for making such a great project!

**Comment by le-doux** [comment]
thanks for the suggestion @tupini07 :)

I understand where you're coming from, but I don't currently have plans to add a virtual d-pad so I'm going to close this issue
