### ISSUE TITLE
Probably typo on bitsy.js parseWorld - double equals instead of triple equals

### ISSUE THREAD

**Issue by david-c14** [le-doux/bitsy#147]
https://github.com/le-doux/bitsy/blob/47114fd246892bc15ac6344b7f2dcfa8bfc02caf/editor/script/engine/bitsy.js#L770

It looks to me that the test for `PAL` entries in the gamedata while parsing the world should be a strict equality test, as are all the others.

**Comment by le-doux** [comment]
good catch! I'll fix this with the next update :)

**Comment by le-doux** [comment]
this is fixed now - thanks again for the tip! :)

https://github.com/le-doux/bitsy/commit/c961d78c90aee6c469e745073f57a256639737b1
