### ISSUE TITLE
visual editing of greater than or equal to and less than or equal to broken in conditions in version 6

### ISSUE THREAD

**Issue by lexaay** [le-doux/bitsy#15]
In addition to issue #14, visual editing of greater than or equal to and less than or equal seems to be broken in conditions.

If you create a condition such as "when variable a>=1", as soon as you edit a different sprite and come back to the previous sprite, the condition is changed to "when custom=1". See attached screenshot. 

I believe what is happening is when ">=" is chosen, the dialog editor creates the code >  =" rather than ">=", which later gets parsed back to a custom expression. For the above example, this is the log in the javascript console:

SERIALIZE ADVANCED DIALOG
editor.js:3555 SERIALIZE DIALOG SPR_0
script.js:1474 CREATE EXPRESSION --- a >= 1
script.js:1474 CREATE EXPRESSION --- a 
script.js:1474 CREATE EXPRESSION --- = 1
script.js:1474 CREATE EXPRESSION ---  1
editor.js:3552 SERIALIZE ADVANCED DIALOG
editor.js:3555 SERIALIZE DIALOG SPR_0

and the code window shows:

I'm a cat{
  - a >  = 1 ?
    hello
  - else ?
    goodbye
}

When the code is parsed and the dialog editor repopulated upon changing sprites, the "> =" is not parsed as ">=", and the condition is shown as "custom".

<img width="200" alt="XPsANP" src="https://user-images.githubusercontent.com/3497492/56341806-ce1fac80-61e8-11e9-8782-39f473bb7d64.png">
<img width="200" alt="a56Dy+" src="https://user-images.githubusercontent.com/3497492/56341814-d2e46080-61e8-11e9-9b2e-37d0ec2cb2f1.png">

**Comment by le-doux** [comment]
thanks for the write-up! I'm looking into this one

**Comment by le-doux** [comment]
ok I've got a fix for this coming in 6.2
