### ISSUE TITLE
Feature request: add item/sprite to room from dialogue

### ISSUE THREAD

**Issue by TennFoot** [le-doux/bitsy#155]
Hi! I had a crack at making a game recently, as I liked the idea of pushing the limits of a seemingly limited engine to create something really interesting. But then I hit a snag - many things I wanted to do required the ability to add an item to a room at a specific location via dialogue.

Unfortunately, there was no such feature, at least not without hacks. Which surprised me - such a feature would be really useful even for the simple projects bitsy seems to have been designed for. For example, it would allow a bitsy user to make a key appear in a room when you talk to an NPC, for instance, without having to do the laborious workaround of making a copy of the room. Would it be possible to add this in? 
Thanks in advance.

**Comment by le-doux** [comment]
thanks for the suggestion @TennFoot, however, I currently don't have plans to add a feature like this, so I'm closing this issue

I recommend looking at the hacks repo if you want to add feature like this: https://github.com/seleb/bitsy-hacks
