### ISSUE TITLE
playing the game does not work on safari on macOS

### ISSUE THREAD

**Issue by Bubalo1234** [le-doux/bitsy#166]
cannot play the game in the editor in safari on macOS

been like this for 10 min
<img width="1792" alt="Screen Shot 2022-08-23 at 4 50 16 PM" src="https://user-images.githubusercontent.com/80659275/186285595-a8b4836d-81e7-4286-be2d-544f8fc00cf4.png">

**Comment by le-doux** [comment]
thanks for the report - I'll look into it!

**Comment by Bubalo1234** [comment]
also btw editing sound does not work on both chrome and safari for macOS

**Comment by le-doux** [comment]
pretty sure this is fixed - can reopen if not
