### ISSUE TITLE
Harden parsing of object id's.

### ISSUE THREAD

**Issue by ace-dent** [le-doux/bitsy#187]
From testing specifically for `Tiles` but may affect other objects...

1. Copy and paste tile data (from an external source), with a punctuation symbol for the tile id- `TIL $`
2. The tile functions correctly, may be edited and placed on the map. Game seems to play ok. So far, so good.
3. Bug: when now using the editor to create a new tile, the automatically assigned id is set to `NaN`.

It may be naive to use punctuation symbols, (e.g. `.$+-#`), but they may be desirable, as they will never clash with the current base36 id system. 

Proposal: 

- Either prevent or warn the user if using id's containing symbols outside of the base36 range (`0-9,a-z/A-Z`); or -
- Make the id auto numbering robust to their presence.

Further problem, causing corruption of map data: The comma `,` symbol is not blocked! The tile can be added to the map, but on Playing will break the map array which depends on the symbol as a value separator. The editor / IDE should not allow an id of `,`.

**Comment by le-doux** [comment]
thanks for the bug report @ace-dent and for the detailed write-up!

my instinct is to continue to allow characters outside the base36 range since it's been allowed for so long, but just have the auto numbering system skip them

definitely need to disallow `,` though

thanks again for your help!

**Comment by ace-dent** [comment]
Thanks for reviewing! Presumably there may be other 'poison' characters like `#` or `!` that have special parsing?...

**Comment by le-doux** [comment]
this doesn't break typical workflows so it's not a high priority to fix right now - thanks again for the work investigating!
