### ISSUE TITLE
Multiple {pg} (pagebreak) commands break dialogue execution

### ISSUE THREAD

**Issue by ker0chan** [le-doux/bitsy#190]
Parts of dialogues can be omitted or replaced by empty dialogue boxes when `{pg}` commands are used in succession, without any text between them. This includes cases where a command exists between the two `{pg}`s.

---

A simple reproduction would be this dialogue:
```
hello{pg}{item "0" 10}{pg}world
```
The expected result is a textbox containing "hello" followed by one containing "world" (with the second `{pg}` understandably requiring an additional user input).

Instead, we only get a textbox containing "hello", followed by an empty textbox, omitting the "world" text entirely. Note that the `item` command is properly executed.

---
The smallest problematic example is:
```
hello{pg}{pg}world
```
This results in a similar behaviour, with an empty textbox and "world" never being displayed.

**Comment by ker0chan** [comment]
Looking for duplicates in case it helps:
This feels similar to issue #84, with `{pg}` improperly messing with the page count.
Issue #175, while not mentioning `{pg}` at all, also describes similar symptoms (empty dialogue box).

**Comment by le-doux** [comment]
thanks for the bug report @ker0chan - all the details are super helpful! it's certainly weird/buggy that the "world" gets omitted entirely :(

**Comment by le-doux** [comment]
fixed! :D
