### ISSUE TITLE
Colors don't change in map after they are set

### ISSUE THREAD

**Issue by TheFudge** [le-doux/bitsy#192]
Currently (I tested it on chrome, firefox, edge and downloaded from GitHub) when you change the color of the sprite **the map will not change** unless I change a pixel on a sprite. 
![bitsybug](https://user-images.githubusercontent.com/4525638/197795341-635ceab1-0a78-44cb-9ea7-fa4cd9c68785.gif)

Is there a fix for that?

**Comment by TheFudge** [comment]
I found this closed issue here and in that older version the bug is fixed, so it seems the problem has reemerged again. 
https://github.com/le-doux/bitsy/issues/129

**Comment by le-doux** [comment]
this should be fixed now with #203
