### ISSUE TITLE
There have problems after importing data from pixsy 

### ISSUE THREAD

**Issue by XantheHer** [le-doux/bitsy#193]
Pictures transcoding by pixsy can't normaly display in bitsy game now.

**Comment by le-doux** [comment]
hi @XantheHer - thanks for reporting this!

can you give me some more details about this issue? after you use pixsy, what steps do you take to the data to your bitsy game?

additionally if you have an example of broken game data that you could share, that would also be helpful!

**Comment by le-doux** [comment]
I think I found a fix for this! will be part of the next update :)
