### ISSUE TITLE
Animation frames issues in the editor

### ISSUE THREAD

**Issue by velvet-dream** [le-doux/bitsy#201]
Hello,

I noticed a few issues with animation frames in the editor.

Sometimes, when I alt+click on a tile in the room to select it, some of the black indicators are replaced by random frames I have drawn, like below:

![Screenshot 2022-11-24 at 15-00-41 Bitsy Game Maker by ledoux](https://user-images.githubusercontent.com/62705392/203802666-d9306efe-e082-432c-accd-23f7a6b61fc7.png)
*before selecting*

![Screenshot 2022-11-24 at 15-00-52 Bitsy Game Maker by ledoux](https://user-images.githubusercontent.com/62705392/203802672-4f371934-47ae-4230-b465-5f8edf95ce62.png)
*after selecting (alt+click). two of the black indicators are replaced by the avatar and another tile.*

If I select another tile, the bug still happens. This seems to happen after drawing some tiles, even though I am not sure how to make this bug happen.

Another issue I have noticed is that sometimes, the animation frame speed in the editor goes extremely fast for some reason. I tried capturing a gif of it but the animation speed is too fast to capture it with with a gif. It happens regurlarly when I am drawing sprites or tiles.

When I try playing the game with this bug happening, I get a blank page instead of my game in the "room" window, like below:

![Screenshot 2022-11-24 at 15-11-51 Bitsy Game Maker by ledoux](https://user-images.githubusercontent.com/62705392/203805107-30d2b9aa-6606-495d-9dc0-0113a0dc5bc9.png)

I need to refresh the browser to make this bug stop.

I don't know if this is a browser-related thing. I am running bitsy on Mozilla Firefox 107.0 (64 bits).

I wish you a good day and hope this bug is no big deal.

**Comment by le-doux** [comment]
thanks for the bug reports @velvet-senpai! this is a pretty weird one, but I made some changes to the graphics system in bitsy 8.0, so it's probably related to those

**Comment by le-doux** [comment]
can't repro these issues anymore - I suspect they may have been fixed by changes to how the renderer caches tiles
