### ISSUE TITLE
decouple PaintTool widget from RoomTool

### ISSUE THREAD

**Issue by pvmm** [le-doux/bitsy#202]
I think it makes sense to decouple PaintTool widget from RoomTool and create an application-wide setting to store the palette:
```
        this.updateCanvas = function() {
                // get palette of selected room
                var selectedRoomId = state.room;
                if (roomTool) {
                        selectedRoomId = roomTool.getSelected();
                }
                if (room[selectedRoomId] === undefined) {
                        selectedRoomId = "0";
                }

                var palId = room[selectedRoomId].pal;
                var palColors = getPal(palId);
                (...)
```

**Comment by le-doux** [comment]
thank you for the suggestion, but I don't think I'm going to make this change right now. while I see the logic in your feedback, I don't currently have time to refactor the way these tools connect unless I'm solving a specific bug. thanks again for your input!

**Comment by pvmm** [comment]
Well, you don't have to close it. Unless you are not planning on fixing it ever. Even so, if you leave it open, someone might fix it for you.
