### ISSUE TITLE
Render animation thumbnail sometimes uses incorrect palette

### ISSUE THREAD

**Issue by nashalexander** [le-doux/bitsy#205]
## Environment
MacOS
Firefox 108.0.2 (64-bit)

## Replicate issue
1. Have two rooms and two palettes, room 0 has palette 0, room 1 palette 1
2. Switch the room editor to room 1
3. Playtest the game, which will begin play testing with room 0
4. Stop play testing. The room editor will switch back to room 1, however the graphical issue below will occur.

## Description
I noticed at some point when editing a game, the animation thumbnails began using the incorrect palette colors and the incorrect values from that palette.

This screenshot displays the room's selected palette in the palette tool.
<img width="300" alt="Screen Shot 2023-01-06 at 10 53 36 PM" src="https://user-images.githubusercontent.com/41334074/211130254-edb6d166-fdaf-4cfe-8289-88fce8f8d915.png">

This screenshot displays the other palette I have, which is not the room's selected palette. Notice how the preview is using the incorrect colors from that palette as well for the background and sprite colors.
<img width="300" alt="Screen Shot 2023-01-06 at 11 13 51 PM" src="https://user-images.githubusercontent.com/41334074/211130577-8eb9dc25-d8c2-4295-bab0-f220c5f9e2b3.png">

## Temporary Fix
Switching from one room and back to the other fixes the issue. So I'm assuming there was some issue that created a mismatch between the stored room id and the actual room tool's id.

**Comment by le-doux** [comment]
thanks for the bug report and the detailed repro steps @nashalexander! this will definitely help me investigate :)

**Comment by le-doux** [comment]
doesn't repro anymore - I think changes I made to how the renderer caching works may have fixed this one
