### ISSUE TITLE
Clicking into draw window immediately after typing name of tile/sprite/item erases name

### ISSUE THREAD

**Issue by jthyer** [le-doux/bitsy#215]
Whenever I create a new tile, sprite, or item, I first enter its name, then I start drawing it. When I do this, the name is erased and replaced with the default name. Then I need to reenter the name. The only way around this is to remember to click outside the draw window between entering the name and drawing the image.

**Comment by Lukenickerson** [comment]
It looks like the `e.preventDefault();` in `onMouseDown` (https://github.com/le-doux/bitsy/blob/main/editor/script/paint.js#L50) is stopping the `change` event from firing `on_drawing_name_change`. It might be the case that `e.preventDefault();` isn't needed as long as the button clicked is the main/left one.

**Comment by le-doux** [comment]
thanks for the report John! and the investigation Luke :)

this seems pretty straightforward- I should be able to fix it in the next update

**Comment by le-doux** [comment]
this is fixed! thanks for the bug report <3
