### ISSUE TITLE
Proposal: Implement webGL color picker (I'll do it, just looking to know if it's something you'd want)

### ISSUE THREAD

**Issue by zachHixson** [le-doux/bitsy#216]
The current color picker is low res, blurry, and prone to aliasing. Obviously this is because color pickers suck to program due to the slow HSV calculations needing to be done for every pixel, but these can be done extremely quickly in shader.

I just recently implemented a very simple webGL color picker into my own engine, and definitely wouldn't mind implementing something similar into Bitsy.

- It'd be webGL 1, so it would support old devices, and work when running direct from an HTML file
- Since the color wheel would be standalone, the code would be very simple
- Considering there's only ever one color wheel at a time I could optimize it so that the webGL context is cached, meaning shader compilation would only ever happen on page load. 

Let me know if you'd be interested in this and I'll get on it.

**Comment by le-doux** [comment]
thanks for the offer Zach! I really appreciate it :)

unfortunately I have to turn you down: I have plans to revamp the color picker UI already and I don’t want to make anyone do a bunch of work just to have it replaced soon after
