### ISSUE TITLE
Grid view for rooms should be persistent 

### ISSUE THREAD

**Issue by ace-dent** [le-doux/bitsy#217]
The option to show/hide a grid in the `room` editor, does not persist between sessions.
e.g. Refresh the browser tab to see the setting reset.
This *does* work for the tile editor.

May be a regression from issue #97 ?

**Comment by le-doux** [comment]
thanks for the bug report! can’t remember if I implemented this for rooms or not but I definitely should :)

**Comment by le-doux** [comment]
this will be in the next update!
