### ISSUE TITLE
Can no longer add `game data` directly

### ISSUE THREAD

**Issue by ace-dent** [le-doux/bitsy#218]
With the `game data` panel open:
- Copy and paste TIL data for an unassigned tile, or even over an existing tile.
- When clicking into the room editor, any changes are lost. 
- This worked previously and was convenient to exchange images.

e.g.
```text
TIL a
10101010
11011101
10101010
01110111
10101010
11011101
10101010
01110111
NAME bayerdither10
```

**Comment by le-doux** [comment]
this one sounds really bad - thanks for letting me know!

**Comment by le-doux** [comment]
doesn't repro anymore
