### ISSUE TITLE
Repeated "Uncaught TypeError: Cannot set properties of undefined (setting '0')" prevents testing the game

### ISSUE THREAD

**Issue by jontopielski** [le-doux/bitsy#223]
Hi, I seem to get the following error every ~10 minutes or so of using the engine and have to refresh to be able to hit play:
![image](https://github.com/le-doux/bitsy/assets/6269590/1103877e-17a4-4d51-9e74-7118e85639a1)

If I try to play, the window just gets stuck with this:
![image](https://github.com/le-doux/bitsy/assets/6269590/7aebe49c-73a5-4459-8b13-a803e282025d)

Also, I notice every animation jitters extremely quickly. Not sure if that might be useful for debugging. Thanks for taking a look!

**Comment by le-doux** [comment]
thanks for the bug report! looks like a problem with the blip tool - I'll see what I can find :)

**Comment by le-doux** [comment]
unfortunately I couldn't repro this issue :(

I'm hoping it was fixed with the other renderer caching bugs, but if you see this again, please open a new issue to let me know!
