### ISSUE TITLE
blip-o-matic don't react on changing droplist "generator"

### ISSUE THREAD

**Issue by Shamancs** [le-doux/bitsy#233]
I try it in Chrome.
When I change droplist "generator" is nothing changed in sound-diagram and game data, so I can't create other beep models (
Example on pictures below:
![2](https://github.com/le-doux/bitsy/assets/2226186/3ca29f97-4ebd-4950-a549-3bdad905f07b)
![1](https://github.com/le-doux/bitsy/assets/2226186/fc6a5cac-403d-4db5-8291-429f034f6beb)

**Comment by nashalexander** [comment]
It appears you need to create a new sound file with the `+` button for the generator to work. Not sure what the design choices are here, but I could see adding a small `generate` button next to the drop down to be helpful. That way you wouldn't overwrite your current sound on accident, but could regenerate if desired.

**Comment by le-doux** [comment]
@nashalexander is right that is working as designed although I agree it’s not intuitive - I like the solution of adding a regenerate button and I’ll merge that PR soon! thank you both!

**Comment by le-doux** [comment]
closing since a change addressing has been merged into the branch for the next version :)
