### ISSUE TITLE
Glitch - all visible tiles change to sprite design when editing a new sprite / avatar disappears

### ISSUE THREAD

**Issue by bibliomancer-games** [le-doux/bitsy#250]
Hi! I've found a strange glitch occurring since the last bitsy update -- this has happened for me on both Mac and PC, as well as on Firefox and Chrome, so I'm not sure where it's coming from. Haven't noticed anyone else posting about it either.

Essentially, when I create a new sprite and begin editing the design, bitsy will automatically replace all of the existing tiles with that sprite and remove the avatar from the room. Upon reloading the page, these changes are reverted -- but it happens again as soon as I begin working with a new sprite.

I've also attached a video below to help show what I mean.

https://github.com/le-doux/bitsy/assets/155098673/c26683eb-357a-49c1-b97b-8ae9a2b45f54

Thanks for any/all help or input you can provide! Bitsy rules!

**Comment by kasiagauza** [comment]
@bibliomancer-games same here, in Firefox 119.0.1, Vivaldi/Chrome 6.5.3206.48, and Edge 120.0.2210.91.
Switching rooms helps, but the editor is still unusable in this state.
![bitsy_room_refresh](https://github.com/le-doux/bitsy/assets/8133091/2b75ccd0-0b00-434a-aa29-49e5e11bd85d)

**Comment by le-doux** [comment]
thanks for the bug report! this should be fixed now - please open a new issue though if you see it again :)

**Comment by Brin-o** [comment]
Hello, sadly I'm experiencing this as are a lot of the students i'm teaching in a workshop. I'd say it's more common on firefox and less common on those that are using chromium browsers. I'm using firefox 131.0.3 (aarch64) on an m1 mac.
