### ISSUE TITLE
Exit effect UI discrepancy ("none" option is missing in dialog)

### ISSUE THREAD

**Issue by burke3gd** [le-doux/bitsy#255]
When adding an exit action in a non-exit dialog the option to select "none" for the transition effect is missing. The "none" option is present when using the exits & endings window. Editing the game data to change the effect of the action to "none" or 0 breaks the game.

Thanks for all the hard work on Bitsy!

**Comment by le-doux** [comment]
thanks for the suggestion - this would be a good improvement! :)

**Comment by le-doux** [comment]
I've got this working - will be released with the next update!
