### ISSUE TITLE
Blank Tools and Room Tool Gone

### ISSUE THREAD

**Issue by Bluegames13** [le-doux/bitsy#264]
I've been working on a school project in bitsy recently, but today I refreshed the page because some of my new tiles weren't showing up but then all the tools were empty and the room tool was missing completely.  I've tried restarting my computer, but the website itself just won't fix. 
![Screenshot (14)](https://github.com/le-doux/bitsy/assets/168045211/f67d3a17-515a-444e-9cb7-aacc878a7fa0)

**Comment by ace-dent** [comment]
@Bluegames13 - did you save your work from the website? I've also occasionally lost a project when the site is updated... but I'd wait to see what the community advises... you can also post to the bitsy [forum](https://itch.io/board/2436112/bitsy) for help. Good luck!🤞

**Comment by le-doux** [comment]
sorry to hear about this - it sounds frustrating!

I would suggest trying to clear your browser's cache to see if that resolves the issue. here's how to do it in firefox (other browsers should be pretty similar): https://support.mozilla.org/en-US/kb/how-clear-firefox-cache

I *don't* think this should delete your game, but to be safe you can open the browser console and type `JSON.parse(localStorage.getItem("game_data") ) `. copy the results into a text file and save it with the extension `.bitsy` and you should be able to load your game back into the editor once everything is fixed.

let me know if these steps fix the issue :)

**Comment by le-doux** [comment]
I think a cache reset should fix this so I'm going to close this issue, but if you still see the problem after resetting your cache please open a new one and let me know! thanks again for the report :)
