### ISSUE TITLE
clicking "room" bar repeatedly messes up UI

### ISSUE THREAD

**Issue by le-doux** [le-doux/bitsy#27]
https://itch.io/t/228280/weird-ui-behaviour

**Comment by Lukenickerson** [comment]
Could not reproduce in v6.4 with latest Chrome.

**Comment by zachThePerson** [comment]
Could also not reproduce in latest Firefox or Chrome

**Comment by le-doux** [comment]
thanks @Lukenickerson and @zachHixson for trying to repro this bug! :) I'm going to close this as not repro-ing and it can be re-opened if someone else reports it
