### ISSUE TITLE
editing game while in play mode causes weird behavior

### ISSUE THREAD

**Issue by le-doux** [le-doux/bitsy#28]
https://itch.io/t/219422/say-doesnt-respect-text-tags-editing-dialogue-while-game-is-running

**Comment by le-doux** [comment]
related issue: https://itch.io/t/164547/typing-while-the-game-is-running-is-inconsistent

**Comment by le-doux** [comment]
related feedback: it's easy to forget whether you are in play or edit mode
https://itch.io/t/152890/some-bugs-ux-annoyances

**Comment by zachThePerson** [comment]
Graying out and locking the rest of the interface while playing would be fantastic. I'm currently running a game design club at the school where I work and the #1 issue is kids editing things while "playing," and then losing 15 minutes worth of progress because Bitsy didn't save their changes.

**Comment by Lukenickerson** [comment]
I think some of the changes do effect the game while it's running (like color), so it might not be good to disable/locking all interfaces. Is it possible to come up with a list of what should be locked vs. not locked when the game is running?

**Comment by zachThePerson** [comment]
I agree, and also think being able to view / change variables is cool too. However, other than variables, I can't think of any actual reason you would _need_ to change anything while the game is running, as any room can be viewed at any point in time, so it's just as easy to tweak colors when you are not playing.

The only two interface windows that would benefit from being "unlocked," (at least with the way Bitsy currently functions), would be Inventory, and "Record GIF." I think it would be safe to lock all other interfaces without causing any issues.

**Comment by Lukenickerson** [comment]
I added a background shading effect in https://github.com/le-doux/bitsy/pull/56 which I think is a good first step.
@le-doux -- Is this something you would merge into master?

**Comment by le-doux** [comment]
this issue has been fixed (you can't edit in play mode anymore)
