### ISSUE TITLE
gif recording doesn't capture text in Chrome

### ISSUE THREAD

**Issue by le-doux** [le-doux/bitsy#30]
https://itch.io/t/196742/issue-with-gif-recording

**Comment by le-doux** [comment]
couldn't repro this on Chrome on MacOS.. will have to try on Windows 10

**Comment by zachThePerson** [comment]
could not reproduce on Chrome or Firefox in Windows 10

**Comment by le-doux** [comment]
thanks for trying in windows zach! I'll close this
