### ISSUE TITLE
room names aren't saved or not imported from game data

### ISSUE THREAD

**Issue by le-doux** [le-doux/bitsy#31]
https://itch.io/t/158872/bitsy-v40-bugs (check in thread for details)

**Comment by Lukenickerson** [comment]
Discussion from that link: 

> hey! So due to this new update all the old room names disappeared and although you can write a name into the room boxes. They're not saved in any way. Because of this I can no longer place any new exits and none of the rooms have any names at all anymore. 

But it didn't seem like it could be reproduced.

**Comment by le-doux** [comment]
wontfix: doesn't repro
