### ISSUE TITLE
dragging beyond edge of paint canvas causes weird behavior

### ISSUE THREAD

**Issue by le-doux** [le-doux/bitsy#36]
dragging on the sprite editor causes page elements to be selected

after dragging from the sprite editor to outside it, then back inside, no more pixels will be placed

https://itch.io/t/158872/bitsy-v40-bugs

**Comment by synth-ruiner** [comment]
looks like this is fixed?

**Comment by le-doux** [comment]
yup this has been fixed in recent versions! :)
