### ISSUE TITLE
No `package.json`

### ISSUE THREAD

**Issue by seleb** [le-doux/bitsy#41]
hey adam! i noticed that 3ec59e3ad9ea8667cf6495a00a0085076043a24d removed the `package.json` which was being used for some electron stuff. would it be possible to add one back in which has just the basic metadata? e.g.:

```json
{
  "name": "bitsy",
  "version": "6.1.0",
  "description": "make tiny games, worlds, and stories",
  "author": "Adam Le Doux"
}
```

idk if there's any intent to publish bitsy as a module, but the presence of a `package.json` with the bare minimum allows it to be used more easily with other tooling (e.g. you can use the npm CLI to install a github repository directly, but it still looks for the `package.json`)

there is also a `license` field, which would be an opportunity to address #5 if one is decided

**Comment by Lukenickerson** [comment]
PR https://github.com/le-doux/bitsy/pull/57 should resolve this.

**Comment by le-doux** [comment]
leaving this on the backlog, since to address as part of improvements to release workflows :)
