### ISSUE TITLE
Rooms without a defined palette break

### ISSUE THREAD

**Issue by seleb** [le-doux/bitsy#42]
pretty minor issue but may be confusing for folks who run into it: if you have a room defined in gamedata without a `PAL` entry, or a `PAL` defined that doesn't actually exist, bitsy will throw errors and fail to render (in both the editor and the exported game).

i noticed it while porting some old gamedata to a newer version of bitsy (guessing palette was optional in earlier versions?), but it can also happen if you're editing gamedata directly (which is currently the only way to delete palettes). it would probably be best to automatically assign the first palette to them in this case to avoid the error.

**Comment by le-doux** [comment]
huh yeah, it should probably default to something instead of breaking!

**Comment by le-doux** [comment]
ok I'll have a fix for this in the next version :)
