### ISSUE TITLE
no way to tell which of many sprites is on-screen

### ISSUE THREAD

**Issue by le-doux** [le-doux/bitsy#45]
if you have a lot of duplicates it's hard to keep track!
https://itch.io/t/152890/some-bugs-ux-annoyances

**Comment by Ragzouken** [comment]
this is somewhat less of a problem now that you can alt-click to pick a sprite and see which it is

**Comment by le-doux** [comment]
thanks @Ragzouken - that's true! I'm closing this issue :)
