### ISSUE TITLE
Touch controls on iOS are still broken

### ISSUE THREAD

**Issue by Ayolland** [le-doux/bitsy#47]
Swiping up or down will still scroll scroll the parent page before activating any Bitsy controls. 
I do not have an Android device handy to test, but can confirm this is broken on iOS Chrome and Safari.

This is (AFAIK) because these browsers do not allow you to prevent the default touch event on the body element.

Borky's solution to this problem is to create a div in JS, inline-styled to be entire viewport and above the game canvas, and attach the eventListener to that. I'm sure there are other solutions too, ofc.

Link to video of current mobile behavior: Note the scrolling in the background and the 'popping' related to the top-bar.

https://www.dropbox.com/s/n0pwoyyti73wdpo/touch_controls.MP4?dl=0

**Comment by Ayolland** [comment]
Further investigation suggests this is an iOS issue only, which makes sense, I guess.

**Comment by le-doux** [comment]
@Ayolland are you up for trying to fix this one?
