### ISSUE TITLE
All black room/paint windows and no data after importing saved HTML file

### ISSUE THREAD

**Issue by Ayolland** [le-doux/bitsy#48]
Occasionally, Bitsy seems to be saving HTML files that run fine in the browser, but bug out the editor when imported back in.

Upon importing one of these files, the room window and paint windows show all black, and the game-data shows entirely blank. However, if you open up the html file, and copy the game-

data into the editor, the game is restored without any apparent issues. Saving the game after pasting in the game-data this way then creates a file with double closing script tag after the font-data script, however this new file still cannot be imported back into the editor.

Attached is an example of a bugged game file:
[broken.html.zip](https://github.com/le-doux/bitsy/files/3298930/broken.html.zip)

**Comment by le-doux** [comment]
thanks for the bug report! I found a fix for this and I will update soon

sorry I'm just getting to it now :|

**Comment by Moos-vanlangendonck** [comment]
how
