### ISSUE TITLE
License

### ISSUE THREAD

**Issue by BozoDel** [le-doux/bitsy#5]
Hey, I noticed there's no license... =P

**Comment by lordofduct** [comment]
I want to +1 this.

What am I allowed to do with this source? Is it free for all use (MIT/Apache license?), is it open-but stuck open (GPL/GNU), what's up?

My artist likes tinkering with this, but if we can't utilize it commercially at all, it's sort of just pointless to invest any sort of time in it.

**Comment by TeddyDD** [comment]
License that allows tinkering would be nice. Currently we can use Bitsy as-it but legally we are not allowed to change single line of code in it.

**Comment by blinry** [comment]
I also noticed that there is no license! :) Care to clarify?

**Comment by tuxayo** [comment]
Question asked on Twitter: https://twitter.com/tuxayo/status/1157241291790569473

**Comment by le-doux** [comment]
hey folks, thanks for the good question, and I'm sorry for the silence on my part! for a while, I was just a little intimidated by all the license options out there. however, as of today, bitsy is now officially under the MIT license :) happy tinkering!
