### ISSUE TITLE
Feature Request: ‘Random’ List Type (like the old shuffle)

### ISSUE THREAD

**Issue by Ayolland** [le-doux/bitsy#51]
It came up in discussion that ‘shuffle’ lists now actually shuffle their list items instead of randomly selecting one. This is nice, makes dialogue a little more natural, and opens up new gameplay opportunities.

BUT many people were using the shuffle as a RNG in games, which it no longer works for, and there’s no really feasible way to add RNG back into Bitsy without hacks. It would great if there was a list type ‘random’ that had the old shuffle behavior, and just returned a random item.

**Comment by le-doux** [comment]
thanks for the suggestion @Ayolland! I'm going to leave this one on the backlog to consider next time I work on the dialog tool
