### ISSUE TITLE
Feature request: undo

### ISSUE THREAD

**Issue by octachrome** [le-doux/bitsy#52]
I'm surprised no one else has requested this. The number of times I accidentally move an exit instead of an entrance, or accidentally move the avatar into a different room. An undo button would be amazing.

**Comment by dnegrin** [comment]
I agree, it's easy to overwrite a sprite.

Would be very helpful for my games and the games I'm teaching to students.

**Comment by le-doux** [comment]
thanks for the suggestion @octachrome and @dnegrin - I agree this would be a major improvement :)

I'm leaving this issue open since I'm interested in tackling this someday, _but_ this feature would require a lot of refactoring, so I don't have near term plans to implement it
