### ISSUE TITLE
Feature Request: Adding some basic "nescessity," hacks natively into Bitsy

### ISSUE THREAD

**Issue by zachHixson** [le-doux/bitsy#53]
I know that Bitsy is supposed to be an engine where the goal is to limit you and let creativity shine, but I can't help but feel it's missing a couple of really small features that would still fit with that goal.

The features would be:

- **end / exit from dialog**: The only place conditionals can be made is through dialog, so it's currently impossible to "unlock," the end of the game after completing a certain task. I believe this one is a must.
- **Extended logic operators**: These would allow some more interesting dialog programming, and would give developers just a couple more choices on how they approached a situation. I'm kind of mixed on this one myself as to if it would fit or not, but still posting it here to see what you think.

These have been implemented as "hacks," but I feel like it's really difficult to make something interactive without them.

As a programmer who has already hacked into Bitsy quite a lot with my own games, I would happily work on these features myself (if possible, I haven't looked too deeply into the source yet) I just want to post here to make sure it fits with the future plans of Bitsy before I work on it.

**Comment by Lukenickerson** [comment]
> it's currently impossible to "unlock," the end of the game after completing a certain task

@zachThePerson - What's an example of completing a task?

**Comment by zachThePerson** [comment]
I was thinking some things like where a character goes something like "I can't find my keys, can you find them for me," and then the game either ends, or is let into the next level after they find the character's keys.

**Comment by zachThePerson** [comment]
I kind of need exit / end on dialog atm, so I am just going to go ahead and add it. It seems easy enough.

Also, since there is a "paragraph break," hack I assumed there was no way to break to a new text window, but apparently you can do this by using {br}, so I went ahead and edited my original post.

**Comment by Ragzouken** [comment]
end/exit from dialog is now in bitsy. not sure what the extended logic operators are?

**Comment by le-doux** [comment]
thanks for the discussion y'all! as @Ragzouken said, end and exit from dialog is now in bitsy

I don't have any near term plans to make major changes to parsing dialog scripts, so I think I'm going to leave extended logic operators as a wontfix but I appreciate the feedback :)
