### ISSUE TITLE
Paint vs. Select modes for Map

### ISSUE THREAD

**Issue by Lukenickerson** [le-doux/bitsy#55]
In the map section, there could be a toggle to switch between two modes:

* "paint" mode -- the current behavior where clicking a square places a thing (sprite/item/tile)
   * Would be helpful to show which thing is currently selected / going to be placed
* "select" mode -- where clicking a square would select the thing, same as selecting it from _find drawing_
   * While in select mode, hovering over a thing could give its type and name. This could help solve #45.

**Comment by zachThePerson** [comment]
Currently you can hold ALT and click an object in your room to select it.

You're right though, perhaps an eyedropper tool or something could be added to make it a little easier for new users, or like you said some kind of toggle between "select," and "place."

**Comment by le-doux** [comment]
thanks for the suggestions y'all! this feature was added in 8.0 :)
