### ISSUE TITLE
Feature Discussion: Add / Remove object from dialog. 

### ISSUE THREAD

**Issue by zachHixson** [le-doux/bitsy#58]
I think a way to add a remove objects from dialog would be nice. An example use case would be a door where you have to find a key. The door would be a sprite, and have a conditional dialog where
```
if hasKey
    {delete "keyDoor"}
else
    "The door is locked, and seems to require a key"
```
or
```
if hasIngredients
    {spawn "soup, 10, 5, roomName"}
```
I don't know if the GitHub is a good place ask this, but the discord seems more for the community and less for development so it's the best place I could find. If there is a better place, I will gladly post this there.

Basically I will happily program these features myself, but I want some feedback before I do so that I can implement them in a way that aligns with the goals of the developers.

Questions:
- Should I allow deleting / spawning of items, or just sprites? Sprites would be easy, but removing items might require more input from the user since there might be more than one. The user might need to specify the X/Y location for example. I know Bitsy is built around "simple," so I don't want to make this too complex (unless you are fine with it). If no X/Y is specified, it could just delete the first occurrence. 
- Further, a "swap," function could be added to swap out one object for another. Once spawn / delete is added, this would just combine the two. Again, might not align with the "KISS," mentality of Bitsy though.

**Comment by le-doux** [comment]
thanks for the suggestion and detailed write-up @zachHixson! I don't currently have plans to add a feature like this so I'm going to close the issue, but I recommend checking out the hacks repository if you want to add similar features to your games (I think "edit room from dialog" could help): https://github.com/seleb/bitsy-hacks
