### ISSUE TITLE
Bitsy wont work.

### ISSUE THREAD

**Issue by Suppera12** [le-doux/bitsy#60]
Bitsy for whatever reason just is a permament black screen and i dont know how to fix it other than the ways ive heard and tried and dont work.

**Comment by zachThePerson** [comment]
Are you launching it from the website, or downloaded from github? Are you using the latest beta release, or the stable one?

What OS, Browser, and Version are you using?

Thanks for reporting the issue, but without more information or steps to reproduce, there isn't much anyone can do to help.

**Comment by Suppera12** [comment]
Hello,

I am launching Bitsy from itch.io and am using the stable one.

I am on Windows 10, Using Chrome Version 79.0.3945.88 (Official Build)
(64-bit)

Thats the most information i know at this time.

**Comment by zachThePerson** [comment]
When you see the black screen, press F12 and go to the "Console," tab. See if there are any errors there. If you don't know what the text in the console means, then just copy and paste it here

**Comment by Suppera12** [comment]
Hello again,

Heres some info i think would be important that i found.

Uncaught DOMException: Failed to read the 'localStorage' property from
'Window': Access is denied for this document.
    at start (
https://v6p9d9t4.ssl.hwcdn.net/html/1656531/editor/script/editor.js:714:2)
    at onload (
https://v6p9d9t4.ssl.hwcdn.net/html/1656531/editor/index.html?v=1574335013:51:25
)

 Uncaught TypeError: Cannot read property 'pal' of undefined
    at getRoomPal (bitsy.js:2209)
    at curPal (bitsy.js:2200)
    at RoomTool.drawEditMap (room.js:239)
    at room.js:216

 Uncaught TypeError: Cannot read property 'pal' of undefined
    at getRoomPal (bitsy.js:2209)
    at curPal (bitsy.js:2200)
    at RoomTool.drawEditMap (room.js:239)
    at room.js:216

(Note: The third bit keeps repeatedly happening each second.)

**Comment by zachThePerson** [comment]
Ok, thanks for posting. I'll look into it. In the mean time, try clearing your cookies, or visiting the site in incognito mode and see if that changes anything

**Comment by zachThePerson** [comment]
Also, in the debug console, type `window.localStorage` and see what comes up

**Comment by Suppera12** [comment]
Fixed the problem. it had to do with my browser blocking a very specific
cookie. i allowed the cookie and everything worked normally.

**Comment by zachThePerson** [comment]
Great! Go ahead and close this issue by clicking the "close issue," button to the left of the "comment," button

**Comment by le-doux** [comment]
I'm closing this :) I'm glad you found a solution @Suppera12 and thanks for helping out @zachThePerson!
