### ISSUE TITLE
Cloning a drawing doesn't regenerate thumbnails

### ISSUE THREAD

**Issue by Ragzouken** [le-doux/bitsy#64]
Cloning a drawing from the paint window leaves a broken image until you cause the thumbnails to regenerate by some other action
![image](https://user-images.githubusercontent.com/527158/72006519-bb05ae80-3247-11ea-9975-c301e5aadc10.png)

**Comment by le-doux** [comment]
want to take this one on candle? :)

**Comment by Ragzouken** [comment]
I'll create `PaintTool.duplicateDrawing` to correspond with `PaintTool.newDrawing` (https://github.com/le-doux/bitsy/blob/42a59c273ed6a7d84a3e55e5fc35ff3ff0d579f7/editor/script/paint.js#L330, which does correctly update thumbnails) and amend https://github.com/le-doux/bitsy/blob/f727e186c78530380f484dccf400cd2bacb44a69/editor/script/editor.js#L1273 to use it

**Comment by le-doux** [comment]
tested and verified the fix works! thank you :)
