### ISSUE TITLE
Panels fill entire screen width on iPad

### ISSUE THREAD

**Issue by R25th** [le-doux/bitsy#69]
All panels fill the entire width of the screen on iPad. All panels are reachable because scrolling has been shifted to vertical but each panel is so large that the interface is unusable. I am unable to zoom out any so there is no way to make each panel smaller.
This issue is present in both 6.4 and 6.5 (it is unclear how long as I’ve only been able to test 6.4 as the oldest version.) Issue was tested on an iPad (7th Generation) running iPadOS 13.2.2 on Safari (latest version) and Chrome 80.0.3987.95. (Issue appears exactly the same on Safari and Chrome but I can add Chrome screenshots if needed)
I’m willing to help bug test as needed if an iPad is not accessible on your end. I also don’t know if this qualifies as a bug or a feature request so feel free to treat it however you see fit.
![5CFD6B70-5A66-4F12-BEAB-063800BAAF6F](https://user-images.githubusercontent.com/62527507/77271582-781f7880-6c85-11ea-9b7a-1e9ce9a1f911.png)
![19B05453-E42E-4B16-9AC8-F6664D05011E](https://user-images.githubusercontent.com/62527507/77271400-faf40380-6c84-11ea-9235-c1b82540db36.png)
![DECF783D-1189-424C-8469-36E2340A0D5B](https://user-images.githubusercontent.com/62527507/77271788-f11ed000-6c85-11ea-9618-ea83be6aabca.png)
![64A904FE-8AA1-436C-8E24-971D9C4B6B90](https://user-images.githubusercontent.com/62527507/77271398-f891a980-6c84-11ea-8b71-01cbc23ef34a.png)

**Comment by samuelfine** [comment]
Looks like the huge body font size being set in responsiveStyle.css is causing this issue. Many of the font style rules across the site reference percentages, so starting at a massive `body` font-size of 48px (16px is the "standard") is causing the panels to explode. Literally just commenting out the entire file in index.html appears to fix this, and in combination with my fix for #47, makes Bitsy usable on iPads!

https://github.com/le-doux/bitsy/blob/master/editor/index.html#L17

@le-doux I'm guessing there are reasons why the responsive styling is how it is, so I haven't made a PR yet. But if you're interested, happy to take a swing at resolving this!

**Comment by le-doux** [comment]
thanks @R25th for the detailed report and @samuelfine for the fix! this _should_ be fixed now with the new responsive UI, but we can re-open it if it's still a problem for anyone :)
