### ISSUE TITLE
auto-walk on reset

### ISSUE THREAD

**Issue by seleb** [le-doux/bitsy#7]
Hey, found a little bug in key-handling behaviour while working on some hack stuff.

Repro steps:
1. start game
1. press ctrl+r
1. confirm
1. press a direction key

Result: avatar automatically walks in the direction pressed as if you were holding the key down

Poked around for a few minutes and cause of the bug seems to be that the "r" from the reset gets added to the key list, but the up event is missed (confirm dialog is open at that point; bug fixes itself if you press "r" again while game is running). Could probably be fixed by preventing the "r" from getting added and/or clearing the list on reset.

**Comment by pippinbarr** [comment]
Just to confirm I'm running into this too. If I have time I might try to fix and submit a pull request, but if it's an easy-ish fix at your end all the better.

**Comment by seleb** [comment]
oh i forgot to close this; it was fixed quite some time ago!
