### ISSUE TITLE
it would be nice if "add exit" was smart enough to avoid collisions

### ISSUE THREAD

**Issue by le-doux** [le-doux/bitsy#72]
all exits and endings get stuck on top of each other

**Comment by le-doux** [comment]
still a problem :( something I want to look into next time I work on the exits tool

**Comment by Lukenickerson** [comment]
Would it be enough if a warning were shown like "overlaps with *exit name*"?

![image](https://user-images.githubusercontent.com/3942453/235571835-aca7d8af-647f-427a-b6ee-ea8f7dc86b94.png)
