### ISSUE TITLE
Only game data is downloaded, rather than full game

### ISSUE THREAD

**Issue by KGOrphanides** [le-doux/bitsy#8]
When running Bitsy locally, the download game option exports only the game data that usually lives in the <script> section, rather than the fully functional HTML file required to actually run the game, as exported by the web version.

It's not clear whether this is a bug or a feature, however, or if there's a workaround or alternate setting that I've missed.

The data works perfectly when pasted into a game file created by the version on itch.io.

I'm running it in Chrome 65.0.3325.162 (Official Build) (64-bit) for Linux.

**Comment by le-doux** [comment]
hi thanks for the bug report! this is a side effect of Chrome's cross origin policy, but I have a fix for this now that will be included with the next version :)

**Comment by Design-inator2000** [comment]
Im having this issue with both Chrome and Opera GX. When I hit download it gives me an sql text file titled "html" instead of an actual html file.
