### ISSUE TITLE
My dialog heavy code leads to many unnecesarry clicks for the player

### ISSUE THREAD

**Issue by brancoliticus** [le-doux/bitsy#86]
Namely it leads to 4 I guess extra clicks in the dialog below. And I have that item sprouted all over the map so it counts a lot in the user experience.

This is a link to the game: https://brancoliticus.itch.io/spaceball-nuggets-2

This is the code in question in full right from the dialog window of my item:
<pre>
It is day {say day_night_count}.
  
{day_night_count = day_night_count + 1}

  {
  - days_to_repeal > 0 ?
    {days_to_repeal = days_to_repeal - 1}
}
  {
  - days_to_enact > 0 ?
    {days_to_enact = days_to_enact - 1}
}
  {
  - days_to_repeal == 0 ?
    {no_law_to_punish = "true"}
}
  {
  - days_to_enact == 0 ?
    {no_law_to_punish = "false"}
}
</pre>

**Comment by le-doux** [comment]
thanks for the bug report! I'll take a look at this :)

**Comment by le-doux** [comment]
sorry I never had a chance to revisit this! it's probably too late to be helpful now, but it looks like the issue is there is some extra whitespace in your dialog script.
