### ISSUE TITLE
Touch screen and painting tiles

### ISSUE THREAD

**Issue by hissan-jpg** [le-doux/bitsy#88]
Hi, before version 7.0, I was able to use the touchscreen on my laptop to paint tiles/avatars/sprites etc. as well as place them in a room. Since the release of 7.0, that has stopped - the touch screen only works for the "buttons" in the interface (e.g. opening and closing tools). Would it be possible to bring that back? It really was much easier on my wrists and RSI-afflicted thumbs. Thanks!

**Comment by le-doux** [comment]
thanks for the bug report! I'll see if I can fix it :)

**Comment by le-doux** [comment]
this _should_ be working now! please re-open this issue if it's still broken for you :)
