### ISSUE TITLE
Things go horribly wrong when there is no room with id 0

### ISSUE THREAD

**Issue by Ragzouken** [le-doux/bitsy#9]
One of the most common problems we have to help people with is that bitsy stops functioning if you delete room 0. Despite that I just thought bitsy was broken for a few days before realising it happened to me.

I'm presuming that it would be a very small change to make Bitsy find an arbitrary room rather than specifically room 0, and it would help a lot of people

**Comment by le-doux** [comment]
thanks for adding this issue! I'm going through all my bug backlogs now, to try and catch up on some of the worst issues - this one is definitely a high priority

**Comment by le-doux** [comment]
also, some more notes from the forum about this bug: https://itch.io/t/208741/46-exits-are-no-longer-able-to-be-placed-after-deleting-initial-room

**Comment by le-doux** [comment]
color picker breaks too: https://itch.io/t/186749/colour-picker-broken

**Comment by le-doux** [comment]
It seems like this doesn't break anymore. At least, the old problems don't show up anymore. If anyone has found new things that break when you remove room 0, I'll re-open this bug. :)
