### ISSUE TITLE
everything is black...

### ISSUE THREAD

**Issue by Alien159159** [le-doux/bitsy#94]
![2020-05-27](https://user-images.githubusercontent.com/66024819/83041838-d0ce1180-a038-11ea-8a39-c166aa8e87fe.png)
I have tried to refresh the page but all it will let me do is rename my game :(

**Comment by synth-ruiner** [comment]
there's a cookie warning of some sort in your browser URL bar, what happens when you click on it? it might need permission to access your saved game

**Comment by Alien159159** [comment]
thats just my pc saying that my cookies are enabled
![2020-06-03](https://user-images.githubusercontent.com/66024819/83640126-9c5fd580-a5a3-11ea-8efb-a60eaf64c7f7.png)

**Comment by Alien159159** [comment]
thats just a problem with my pc, no matter what website it is

**Comment by synth-ruiner** [comment]
OK, can you browse to the page and open the developer console (usually by pressing F12 and clicking on the Console tab) and paste all the output here?

**Comment by Alien159159** [comment]
!!!!! NEW RENDERER
explorer.js:366 NEW THUMB RENDERER
gif.js:672 gif encoder initialized!
explorer.js:366 NEW THUMB RENDERER
editor.js:722 BROWSER FEATURES
editor.js:730 color picker supported!
editor.js:750 downloads supported!
editor.js:759 blob supported!
editor.js:827 @@@@@ FLAGGS
editor.js:835 Object
paint.js:120 NEW PAINT TOOL
paint.js:121 Renderer
editor.js:898 MARKER TOOL [object Object]
editor.js:909 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at start (https://v6p9d9t4.ssl.hwcdn.net/html/2290891/editor/script/editor.js:909:2)
    at onload (https://v6p9d9t4.ssl.hwcdn.net/html/2290891/editor/index.html?v=1591301608:54:25)
70bitsy.js:2079 Uncaught TypeError: Cannot read property 'pal' of undefined
    at getRoomPal (bitsy.js:2079)
    at curPal (bitsy.js:2070)
    at RoomTool.drawEditMap (room.js:263)
    at room.js:240
35bitsy.js:2079 Uncaught TypeError: Cannot read property 'pal' of undefined
    at getRoomPal (bitsy.js:2079)
    at curPal (bitsy.js:2070)
    at RoomTool.drawEditMap (room.js:263)
    at room.js:240
getRoomPal @ bitsy.js:2079
curPal @ bitsy.js:2070
RoomTool.drawEditMap @ room.js:263
(anonymous) @ room.js:240
paint.js:187 ?????
3bitsy.js:2079 Uncaught TypeError: Cannot read property 'pal' of undefined
    at getRoomPal (bitsy.js:2079)
    at curPal (bitsy.js:2070)
    at RoomTool.drawEditMap (room.js:263)
    at room.js:240
getRoomPal @ bitsy.js:2079
curPal @ bitsy.js:2070
RoomTool.drawEditMap @ room.js:263
(anonymous) @ room.js:240
paint.js:187 ?????
15bitsy.js:2079 Uncaught TypeError: Cannot read property 'pal' of undefined
    at getRoomPal (bitsy.js:2079)
    at curPal (bitsy.js:2070)
    at RoomTool.drawEditMap (room.js:263)
    at room.js:240
getRoomPal @ bitsy.js:2079
curPal @ bitsy.js:2070
RoomTool.drawEditMap @ room.js:263
(anonymous) @ room.js:240
paint.js:187 ?????
44bitsy.js:2079 Uncaught TypeError: Cannot read property 'pal' of undefined
    at getRoomPal (bitsy.js:2079)
    at curPal (bitsy.js:2070)
    at RoomTool.drawEditMap (room.js:263)
    at room.js:240
getRoomPal @ bitsy.js:2079
curPal @ bitsy.js:2070
RoomTool.drawEditMap @ room.js:263
(anonymous) @ room.js:240
paint.js:187 ?????
33bitsy.js:2079 Uncaught TypeError: Cannot read property 'pal' of undefined
    at getRoomPal (bitsy.js:2079)
    at curPal (bitsy.js:2070)
    at RoomTool.drawEditMap (room.js:263)
    at room.js:240
getRoomPal @ bitsy.js:2079
curPal @ bitsy.js:2070
RoomTool.drawEditMap @ room.js:263
(anonymous) @ room.js:240

**Comment by Alien159159** [comment]
that what you needed? soz i'm very confused

**Comment by synth-ruiner** [comment]
> editor.js:909 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
that's exactly what I suspected was happening - your browser is not permitting Bitsy to access local storage and retrieve your saved game. you'll need to look into your browser settings to allow local storage for this page.

**Comment by Alien159159** [comment]
I apologise but how do I do that?

**Comment by synth-ruiner** [comment]
I don't know what browser you're using (is that Chrome?) but I'd recommend clicking on the cookie icon and seeing what comes up. if that doesn't work, have a search online.

**Comment by synth-ruiner** [comment]
alternatively you can download the [Itch desktop program](https://itch.io/app) and install Bitsy through there.

**Comment by le-doux** [comment]
thanks for the report @Alien159159 and for helping out @synth-ruiner :) this should be fixed now thanks to work by @seleb - if you encounter the issue again though, please re-open this issue!
