### ISSUE TITLE
dialog editor visually noisy 

### ISSUE THREAD

**Issue by Ragzouken** [le-doux/bitsy#98]
i think the alternating frames of blue and white are making it more difficult to read:

![image](https://user-images.githubusercontent.com/527158/85432231-934a9e80-b57a-11ea-9bb5-96f569fe8807.png)

i'm wondering if you would consider something like these, using many fewer borders and lines:

![image](https://user-images.githubusercontent.com/527158/85433770-d60d7600-b57c-11ea-922d-127ecf7b78e8.png)

![image](https://user-images.githubusercontent.com/527158/85539991-5cbe6380-b60e-11ea-9e2d-22d9143a6be2.png)

**Comment by le-doux** [comment]
thanks for the suggestion @Ragzouken! I'll keep this on the backlog to look into for the next time I do a usability pass on the dialog editor :)
